# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/antonyalkmim/workspace/PHPtoCpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/antonyalkmim/workspace/PHPtoCpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/antonyalkmim/workspace/PHPtoCpp/CMakeFiles /home/antonyalkmim/workspace/PHPtoCpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/antonyalkmim/workspace/PHPtoCpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PHPtoCpp

# Build rule for target.
PHPtoCpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PHPtoCpp
.PHONY : PHPtoCpp

# fast build rule for target.
PHPtoCpp/fast:
	$(MAKE) -f CMakeFiles/PHPtoCpp.dir/build.make CMakeFiles/PHPtoCpp.dir/build
.PHONY : PHPtoCpp/fast

list.o: list.cpp.o

.PHONY : list.o

# target to build an object file
list.cpp.o:
	$(MAKE) -f CMakeFiles/PHPtoCpp.dir/build.make CMakeFiles/PHPtoCpp.dir/list.cpp.o
.PHONY : list.cpp.o

list.i: list.cpp.i

.PHONY : list.i

# target to preprocess a source file
list.cpp.i:
	$(MAKE) -f CMakeFiles/PHPtoCpp.dir/build.make CMakeFiles/PHPtoCpp.dir/list.cpp.i
.PHONY : list.cpp.i

list.s: list.cpp.s

.PHONY : list.s

# target to generate assembly for a file
list.cpp.s:
	$(MAKE) -f CMakeFiles/PHPtoCpp.dir/build.make CMakeFiles/PHPtoCpp.dir/list.cpp.s
.PHONY : list.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/PHPtoCpp.dir/build.make CMakeFiles/PHPtoCpp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/PHPtoCpp.dir/build.make CMakeFiles/PHPtoCpp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/PHPtoCpp.dir/build.make CMakeFiles/PHPtoCpp.dir/main.cpp.s
.PHONY : main.cpp.s

node.o: node.cpp.o

.PHONY : node.o

# target to build an object file
node.cpp.o:
	$(MAKE) -f CMakeFiles/PHPtoCpp.dir/build.make CMakeFiles/PHPtoCpp.dir/node.cpp.o
.PHONY : node.cpp.o

node.i: node.cpp.i

.PHONY : node.i

# target to preprocess a source file
node.cpp.i:
	$(MAKE) -f CMakeFiles/PHPtoCpp.dir/build.make CMakeFiles/PHPtoCpp.dir/node.cpp.i
.PHONY : node.cpp.i

node.s: node.cpp.s

.PHONY : node.s

# target to generate assembly for a file
node.cpp.s:
	$(MAKE) -f CMakeFiles/PHPtoCpp.dir/build.make CMakeFiles/PHPtoCpp.dir/node.cpp.s
.PHONY : node.cpp.s

transpiler.o: transpiler.cpp.o

.PHONY : transpiler.o

# target to build an object file
transpiler.cpp.o:
	$(MAKE) -f CMakeFiles/PHPtoCpp.dir/build.make CMakeFiles/PHPtoCpp.dir/transpiler.cpp.o
.PHONY : transpiler.cpp.o

transpiler.i: transpiler.cpp.i

.PHONY : transpiler.i

# target to preprocess a source file
transpiler.cpp.i:
	$(MAKE) -f CMakeFiles/PHPtoCpp.dir/build.make CMakeFiles/PHPtoCpp.dir/transpiler.cpp.i
.PHONY : transpiler.cpp.i

transpiler.s: transpiler.cpp.s

.PHONY : transpiler.s

# target to generate assembly for a file
transpiler.cpp.s:
	$(MAKE) -f CMakeFiles/PHPtoCpp.dir/build.make CMakeFiles/PHPtoCpp.dir/transpiler.cpp.s
.PHONY : transpiler.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PHPtoCpp"
	@echo "... list.o"
	@echo "... list.i"
	@echo "... list.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... node.o"
	@echo "... node.i"
	@echo "... node.s"
	@echo "... transpiler.o"
	@echo "... transpiler.i"
	@echo "... transpiler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

